[Addon]
Name=I'm Emoji Picker (handwriting)
Category=Module
Version=
Library=fcitx5imemojipicker-handwriting
Type=SharedLibrary
OnDemand=False
Configurable=True

[Addon/OptionalDependencies]
0=wayland
